version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 40
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "deps"
